# Generated by Django 3.2.4 on 2021-06-11 02:09

from django.db import migrations, models
import django.db.models.deletion
import seller_side.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mobile_number', models.CharField(max_length=155, unique=True)),
                ('otp', models.IntegerField(default=seller_side.models.generateOTP)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('store_link', models.URLField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_side.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=155)),
                ('description', models.TextField(null=True)),
                ('mrp', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_side.store')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('mobile_number', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_side.product')),
            ],
        ),
    ]
