# Generated by Django 3.2.4 on 2021-06-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_link',
            field=models.URLField(default='https:www.online_app.com', max_length=255),
        ),
    ]
